//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop_stock_tracking.Parametreler {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class settings_LocalDB : global::System.Configuration.ApplicationSettingsBase {
        
        private static settings_LocalDB defaultInstance = ((settings_LocalDB)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new settings_LocalDB())));
        
        public static settings_LocalDB Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sst")]
        public string localdb_ {
            get {
                return ((string)(this["localdb_"]));
            }
            set {
                this["localdb_"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sst_db")]
        public string database_ {
            get {
                return ((string)(this["database_"]));
            }
            set {
                this["database_"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ilkmi {
            get {
                return ((bool)(this["ilkmi"]));
            }
            set {
                this["ilkmi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Deneme Personeli")]
        public string default_personel_adi {
            get {
                return ((string)(this["default_personel_adi"]));
            }
            set {
                this["default_personel_adi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Demo")]
        public string default_personel_soyadi {
            get {
                return ((string)(this["default_personel_soyadi"]));
            }
            set {
                this["default_personel_soyadi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Demo")]
        public string default_kullanici_adi {
            get {
                return ((string)(this["default_kullanici_adi"]));
            }
            set {
                this["default_kullanici_adi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234")]
        public string default_sifre {
            get {
                return ((string)(this["default_sifre"]));
            }
            set {
                this["default_sifre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5417925900")]
        public string default_tel1 {
            get {
                return ((string)(this["default_tel1"]));
            }
            set {
                this["default_tel1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("y")]
        public string default_personel_turu {
            get {
                return ((string)(this["default_personel_turu"]));
            }
            set {
                this["default_personel_turu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int loading_value {
            get {
                return ((int)(this["loading_value"]));
            }
            set {
                this["loading_value"] = value;
            }
        }
    }
}
